#!/usr/bin/env bash

# setxkbmap -query | awk '
#     BEGIN{layout="";variant=""}
#     /^layout/{layout=$2}
#     /^variant/{variant=" ("$2")"}
#     END{printf("%s%s",layout,variant)}'

COMMAND=$(xset -q | grep LED | awk '{ print $10 }')

case "$COMMAND" in

 "00000000"|"00000001") LAYOUT="us" ;;

  "00001000"|"00001001") LAYOUT="fr" ;;

    *) LAYOUT="??" ;;

    esac

    echo $LAYOUT

